### PR TITLE
Upload New Logo

### PR DESCRIPTION
**Pull request by mirzazulfan**
I created these logos myself and license them under the same license as the nsupdate.info project's license.

### CODE REVIEW

**Comment by mirzazulfan** [comment]
I created these logos myself and license them under the same license as the nsupdate.info project's license.

**Comment by mirzazulfan** [comment]
You're welcome. It was my pleasure :)

**Comment by ThomasWaldmann** [comment]
@elnappo can you review and integrate this?

**Comment by elnappo** [comment]
Yes, sure.

**Comment by mirzazulfan** [comment]
Hi @elnappo , @ThomasWaldmann Is there still something missing with the file guys?

**Comment by elnappo** [comment]
No sorry everything is fine. Thanks a lot!

**Pull request merged**
