### PR TITLE
src/ based project layout

### PR DESCRIPTION
**Pull request by ThomasWaldmann**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
hmm, coverage broken?

**Comment by ThomasWaldmann** [comment]
@elnappo do you currently have a local test setup, that runs the tests successfully (including the ones which need a dns server setup)?

if so, can you run the code from this PR?

travis seems to be happy, but i don't have a local setup currently.

**Comment by elnappo** [comment]
No, sorry.

**Comment by ThomasWaldmann** [comment]
ok, then i'll just merge as is.

this likely will cause some merge conflicts, but fixing the smaller PRs is likely easier than vice versa.

**Pull request merged**
