### PR TITLE
Updated Bootstrap

### PR DESCRIPTION
**Pull request by vanillajonathan**
Updated Bootstrap from version 3.3.4 to 3.3.5.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
why did you close it? you can also just add another commit to your existing PR (== to same branch).

**Comment by vanillajonathan** [comment]
I don't know how to do that.
I meant to do two separate commits, one for documentation, one for Bootstrap code. But somehow they all ended up in one commit. Then I didn't know how to append the requested change to the existing commit.

**Comment by ThomasWaldmann** [comment]
git checkout thatbranch
change stuff and add it
git commit ...
git push
(git checkout master)

**Comment by vanillajonathan** [comment]
I use the GitHub website, not the Git software do contribute.

**Comment by ThomasWaldmann** [comment]
ah, then you maybe can update it in YOUR repo, in the right branch.

**Comment by vanillajonathan** [comment]
I close this pull request and request that the other pull requests be pulled instead.

**Pull request closed without merging**
